window.PHOTO_MODES = [
  {
    id: "korean",
    icon: "👦",
    name: "韩系日常",
    description: "日常、商场、聚餐、人像都很稳的通透暖白。",
    prompt: "适合日常 / 商场 / 聚餐 / 人像",
    advice: ["曝光 -0.3", "暖白", "奶油色", "自然肤色"],
    keywords: ["韩系", "通透", "自然", "温暖"],
    accent: "#f4cf9a",
    accentSoft: "rgba(244, 207, 154, 0.58)",
    sheetGlow: "rgba(244, 207, 154, 0.42)",
    brightness: 0.72,
    camera: "environment",
    note: "进入相机后轻点屏幕主体，再向下轻滑曝光条到 -0.3。"
  },
  {
    id: "city",
    icon: "🏙",
    name: "城市高级感",
    description: "冷调、高对比、适合酒店商务和城市夜色。",
    prompt: "适合酒店 / 商务 / 夜景",
    advice: ["冷调", "高对比", "屏幕 60%", "深色氛围"],
    keywords: ["冷调", "电影感", "高对比"],
    accent: "#7890b8",
    accentSoft: "rgba(120, 144, 184, 0.52)",
    sheetGlow: "rgba(120, 144, 184, 0.42)",
    brightness: 0.6,
    forceDark: true,
    camera: "environment",
    note: "网页无法直接改系统亮度，会用屏幕暗层模拟 60% 取景环境。"
  },
  {
    id: "selfie",
    icon: "👧",
    name: "女生自拍",
    description: "柔和玫瑰金，适合干净肤色和小红书风自拍。",
    prompt: "建议开启人像模式",
    advice: ["前摄", "亮度 85%", "人像模式", "柔光感"],
    keywords: ["柔和", "玫瑰金", "小红书风"],
    accent: "#e9a7b6",
    accentSoft: "rgba(233, 167, 182, 0.55)",
    sheetGlow: "rgba(233, 167, 182, 0.44)",
    brightness: 0.85,
    camera: "user",
    note: "点前摄入口可直接呼出自拍相机；进入后建议切换人像模式。"
  },
  {
    id: "fresh",
    icon: "🌿",
    name: "清新自然",
    description: "旅行感、清透真实，适合白天户外和自然光。",
    prompt: "适合旅行 / 公园 / 咖啡店 / 自然光",
    advice: ["清透", "真实", "高亮", "浅绿色"],
    keywords: ["旅行感", "清透", "真实"],
    accent: "#93caa6",
    accentSoft: "rgba(147, 202, 166, 0.52)",
    sheetGlow: "rgba(147, 202, 166, 0.42)",
    brightness: 0.9,
    forceLight: true,
    camera: "environment",
    note: "尽量让人物面向窗边或天空反光，画面会更干净。"
  },
  {
    id: "night",
    icon: "🎬",
    name: "夜景电影感",
    description: "黑金、低亮度、城市灯光里的高级氛围。",
    prompt: "适合夜景 / 酒吧 / 城市灯光",
    advice: ["黑金", "亮度 45%", "勿扰专注", "氛围感"],
    keywords: ["黑金", "电影感", "氛围感"],
    accent: "#d4a64f",
    accentSoft: "rgba(212, 166, 79, 0.46)",
    sheetGlow: "rgba(212, 166, 79, 0.38)",
    brightness: 0.45,
    forceDark: true,
    camera: "environment",
    note: "iOS 不允许 PWA 自动开启勿扰；建议从控制中心打开专注模式。"
  }
];
